import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "./ui/navbar";
import Sidebar from "./ui/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} item-jorok relative`}>
        <Providers>
          <Navbar />
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
